pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
    }

    stages {


        stage('Clean workspace') {
            steps {
                cleanWs()
                sh 'git clone https://github.com/Shanawar99/zinougeh.git'

            }
        }

        // stage('Terraform to Spin New EC2 server') {
        //     steps {
        //         // Run Terraform commands
        //         dir('zinougeh/task1/terraform')
        //         {
        //             sh 'terraform init'
        //             sh 'terraform apply -auto-approve'
        //             sleep time: 200, unit: 'SECONDS'
        //             script {
        //                 def EC2_PUBLIC_IP = sh(script: 'terraform output public_ip', returnStdout: true).trim()
        //                 env.EC2_PUBLIC_IP = EC2_PUBLIC_IP
        //                 println(EC2_PUBLIC_IP)
        //             }
        //         }
        //     }
        // }
        
        stage('Ansible to Install MicroK8s') {
            steps {
                dir('zinougeh/task1/microk8s/') {
                    script {
                        env.EC2_PUBLIC_IP="18.209.223.43"
                        def inventoryFile = """
                            [all]
                            ${env.EC2_PUBLIC_IP}
                        """

                        writeFile file: 'temp_inventory.ini', text: inventoryFile

                        sh 'cat temp_inventory.ini'
                        sh 'ls'

                        ansiblePlaybook(
                            inventory: 'temp_inventory.ini',
                            playbook: 'ansible.yml',
                            hostKeyChecking: false
                        )
                    }
            }
        }
    }
}
}